import type {Metadata} from "next";
import Link from "next/link";
import {Footer,Header,Icon} from "./site-components";

export const metadata:Metadata={title:"Personalized Tutoring in Lexington, SC | Miss Arnold’s Tutoring Table",description:"One-on-one reading and math tutoring for Grades 2–7, plus GED and adult math support in Lexington, West Columbia, and online."};
const services=[["book","Reading Support","Phonics, fluency, comprehension, vocabulary, and confidence-building."],["math","Math Support","Foundational skills, problem solving, and academic growth for Grades 2–7."],["cap","GED & Adult Math","Patient, practical support for adults building skills and preparing for exams."],["laptop","Student Resources","A convenient place for current students to access practice and session tools."]] as const;

export default function Home(){return <><Header/><main>
<section className="home-hero"><div className="hero-copy"><p className="pill">Grades 2–7 • GED & adult learners</p><h1>Personalized Tutoring for Reading, Math & <span>Confidence</span></h1><p>Supportive one-on-one tutoring that builds skills, strengthens confidence, and helps learners make meaningful progress.</p><div className="button-row"><Link className="button primary" href="/preassessment">Book a Pre-Assessment</Link><Link className="button secondary" href="/services">View Services <span>→</span></Link></div><div className="trust-row"><span>◆ Individualized support</span><span>◆ Local & online</span><span>◆ Clear $40/hour rate</span></div></div><div className="hero-visual"><div className="hero-photo" role="img" aria-label="Miss Arnold providing one-on-one tutoring at a table"></div><aside><p><strong>Grades 2–7</strong><br/>Reading & Math</p><p><strong>GED & Adult Math</strong><br/>Foundational support</p><p><strong>Online, Library & In-Home</strong><br/>Flexible options</p><p><strong>$40 per hour</strong><br/>Simple pricing</p></aside></div></section>
<section className="services-preview section-wrap" aria-labelledby="services-heading"><div className="section-heading"><p className="eyebrow">Ways I can help</p><h2 id="services-heading">Support for different learners and goals.</h2><p>Every session is designed around the person sitting at the table.</p></div><div className="four-grid">{services.map(([icon,title,text])=><article key={title}><Icon name={icon}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="value-strip section-wrap"><article><Icon name="person"/><div><h3>Personalized Instruction</h3><p>Lessons respond to each learner’s strengths, needs, and goals.</p></div></article><article><Icon name="heart"/><div><h3>Experienced & Compassionate</h3><p>Clear teaching delivered with patience, honesty, and encouragement.</p></div></article><article><Icon name="calendar"/><div><h3>Flexible Scheduling</h3><p>Choose Zoom, library, or approved in-home sessions.</p></div></article></section>
<section className="process-locations section-wrap"><div className="process-card"><p className="eyebrow">A clear beginning</p><h2>How It Works</h2><div className="process-steps"><article><b>1</b><Icon name="calendar"/><h3>Book</h3><p>Request a time that works for you.</p></article><article><b>2</b><Icon name="check"/><h3>Pre-Assess</h3><p>We identify strengths, needs, and goals.</p></article><article><b>3</b><Icon name="book"/><h3>Plan</h3><p>I create an individualized starting plan.</p></article><article><b>4</b><Icon name="person"/><h3>Grow</h3><p>We build skills, confidence, and independence.</p></article></div><Link className="text-link" href="/approach">Learn what to expect →</Link></div><div className="location-card"><p className="eyebrow">Flexible options</p><h2>Where We Meet</h2><article><Icon name="laptop"/><div><h3>Online through Zoom</h3><p>Convenient virtual sessions from home.</p></div></article><article><Icon name="pin"/><div><h3>Lexington County Main Library</h3><p>A public space for focused learning.</p></div></article><article><Icon name="home"/><div><h3>In-Home</h3><p>Lexington and West Columbia; $10 travel fee per visit.</p></div></article><Link className="text-link" href="/locations">View location details →</Link></div></section>
<section className="pricing-about section-wrap"><div className="price-preview"><p className="eyebrow">Simple pricing</p><strong>$40</strong><span>per hour</span><ul><li>One-on-one tutoring</li><li>Reading, math, GED & adult support</li><li>Weekly, biweekly, or monthly payments</li><li>Payment due 24 hours before sessions</li></ul><Link className="button primary" href="/pricing">Pricing & Policies</Link></div><div className="about-preview"><p className="eyebrow">Meet Miss Arnold</p><h2>Professional support with a personal approach.</h2><p>Claire Arnold is a certified South Carolina educator, former K–8 reading interventionist, and experienced one-on-one tutor. As an educator with dyslexia, she understands that capable learners sometimes need information presented differently.</p><Link className="button secondary" href="/about">Read About Miss Arnold <span>→</span></Link></div></section>
<section className="parent-cta"><div><p className="eyebrow">For parents and adult learners</p><h2>Clear information. A comfortable first step.</h2><p>Learn what tutoring includes, what the first session looks like, and how support is personalized before you commit to an ongoing schedule.</p></div><div className="button-row"><Link className="button primary" href="/preassessment">Book a Pre-Assessment</Link><Link className="button secondary" href="/faq">Read Common Questions</Link></div></section>
</main><Footer/></>}
