import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {Footer,Header,Icon} from "./site-components";

export const metadata:Metadata={title:"Personalized Tutoring in Lexington, SC | Miss Arnold’s Tutoring Table",description:"One-on-one reading and math tutoring for Grades 2–7, plus GED and adult math support in Lexington, West Columbia, and online.",alternates:{canonical:"https://cdarnold07-afk.github.io/miss-arnold-s-tutoring-table/"}};
const services=[["book","Reading Support","Phonics, fluency, comprehension, vocabulary, and confidence-building."],["math","Math Support","Foundational skills, problem solving, and academic growth for Grades 2–7."],["cap","GED & Adult Math","Patient, practical support for adults building skills and preparing for exams."],["laptop","Student Resources","A convenient place for current students to access practice and session tools."]] as const;

export default function Home(){return <><Header/><main>
<section className="home-hero"><div className="hero-copy"><p className="pill">Now enrolling • Grades 2–7 & adults</p><h1>Personalized Tutoring for Reading, Math & <span>Confidence</span></h1><p>Patient, one-on-one instruction that meets learners where they are and helps them build skills they can use with confidence.</p><div className="button-row"><Link className="button primary" href="/preassessment">Book a Pre-Assessment</Link><Link className="button secondary" href="/services">View Services <span>→</span></Link></div><div className="trust-row"><span>Individualized support</span><span>Lexington-area & online</span><span>Clear $40/hour rate</span></div></div><div className="hero-visual"><div className="portrait-frame"><Image src="/miss-arnold-s-tutoring-table/hero-students-v2.webp" alt="Three diverse students working together at a library table" fill priority sizes="(max-width: 950px) 88vw, 47vw"/></div><aside><p><strong>Grades 2–7</strong><br/>Reading & Math</p><p><strong>GED & Adult Math</strong><br/>Patient, practical support</p><p><strong>Online, Library & In-Home</strong><br/>Flexible meeting options</p><p><strong>$40 per hour</strong><br/>Straightforward pricing</p></aside></div></section>
<section className="services-preview section-wrap" aria-labelledby="services-heading"><div className="section-heading"><p className="eyebrow">Ways I can help</p><h2 id="services-heading">Focused support for real learning goals.</h2><p>Every session is designed around the learner sitting at the table.</p></div><div className="four-grid">{services.map(([icon,title,text])=><article key={title}><Icon name={icon}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="reading-feature"><div className="reading-photo"><Image src="/miss-arnold-s-tutoring-table/students-reading.webp" alt="Two students enjoying books together in a library" fill sizes="(max-width: 850px) 100vw, 52vw"/></div><div className="reading-copy"><p className="eyebrow">Learning can feel good</p><h2>Build skills, curiosity, and confidence.</h2><p>Tutoring should be focused without feeling stressful. Lessons use clear explanations, supportive practice, and age-appropriate activities that help learners feel successful.</p><Link className="button secondary" href="/services">Explore Tutoring Services <span>→</span></Link></div></section>
<section className="value-strip section-wrap"><article><Icon name="person"/><div><h3>Personalized Instruction</h3><p>Lessons respond to each learner’s strengths, needs, and goals.</p></div></article><article><Icon name="heart"/><div><h3>Experienced & Compassionate</h3><p>Clear teaching delivered with patience, honesty, and encouragement.</p></div></article><article><Icon name="calendar"/><div><h3>Flexible Scheduling</h3><p>Choose Zoom, library, or approved in-home sessions.</p></div></article></section>
<section className="process-band"><div className="section-wrap"><p className="eyebrow">A clear beginning</p><h2>How It Works</h2><div className="process-steps"><article><b>1</b><Icon name="calendar"/><h3>Book</h3><p>Request a pre-assessment time that works for you.</p></article><article><b>2</b><Icon name="check"/><h3>Assess</h3><p>We identify strengths, needs, and learning goals.</p></article><article><b>3</b><Icon name="book"/><h3>Plan</h3><p>I create a personalized plan for a strong start.</p></article><article><b>4</b><Icon name="person"/><h3>Grow</h3><p>We build skills, confidence, and independence.</p></article></div><Link className="text-link" href="/approach">Learn what to expect →</Link></div></section>
<section className="locations-feature"><div className="location-copy"><p className="eyebrow">Flexible options</p><h2>Where We Meet</h2><article><Icon name="laptop"/><div><h3>Online through Zoom</h3><p>Convenient virtual sessions from home. Participants enter only after Miss Arnold admits them.</p></div></article><article><Icon name="pin"/><div><h3>Lexington County Main Library</h3><p>A comfortable public setting for focused learning.</p></div></article><article><Icon name="home"/><div><h3>In-Home</h3><p>Lexington and West Columbia; $10 travel fee per visit.</p></div></article><Link className="text-link" href="/locations">View location details →</Link></div><div className="location-portrait"><Image src="/miss-arnold-s-tutoring-table/one-on-one-tutoring.webp" alt="A student receiving focused one-on-one tutoring at a table" fill sizes="(max-width: 950px) 100vw, 52vw"/></div></section>
<section className="price-band"><div><p className="eyebrow">Simple, transparent pricing</p><strong>$40</strong><span>per hour • one-on-one tutoring</span></div><ul><li>Reading & math support</li><li>GED & adult math</li><li>Online or in person</li><li>Payment due 24 hours before sessions</li></ul><Link className="button cream-button" href="/pricing">Pricing & Policies</Link></section>
<section className="about-feature section-wrap"><div className="about-portrait"><Image src="/miss-arnold-s-tutoring-table/miss-arnold-portrait.webp" alt="Portrait of Miss Arnold" fill sizes="(max-width: 650px) 88vw, 38vw"/></div><div><p className="eyebrow">Meet Miss Arnold</p><h2>Professional support with a personal approach.</h2><p>Claire Arnold is a certified South Carolina educator, former K–8 reading interventionist, and experienced one-on-one tutor. As an educator with dyslexia, she understands that capable learners sometimes need information presented differently.</p><p>Her goal is to create a calm, encouraging space where children and adults can ask questions, strengthen foundational skills, and recognize their own progress.</p><Link className="button secondary" href="/about">Read About Miss Arnold <span>→</span></Link></div></section>
<section className="parent-cta"><div><p className="eyebrow">For parents and adult learners</p><h2>Clear information. A comfortable first step.</h2><p>Learn what tutoring includes, what the first session looks like, and how support is personalized before you commit to an ongoing schedule.</p></div><div className="button-row"><Link className="button primary" href="/preassessment">Book a Pre-Assessment</Link><Link className="button secondary" href="/faq">Read Common Questions</Link></div></section>
</main><Footer/></>}
