import Link from "next/link";
import { Header, Footer, ArrowLink } from "./site-components";

export default function Home() {
  return <><Header/><main>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">Grades 2–7 & adult learners</p><h1>Learning <span>clicks</span> when support fits.</h1><p className="hero-lede">One-on-one tutoring that builds skills, confidence, and independence—in Lexington and online.</p><div className="button-row"><Link className="button primary" href="/preassessment">Request a preassessment <b>→</b></Link><Link className="button secondary" href="/student-hub">Student hub <b>→</b></Link></div></div><div className="hero-photo" aria-label="One-on-one tutoring at a table"/></section>
    <section className="split-paths"><div className="path path-current"><p className="eyebrow light">Already at the table?</p><h2>Current students</h2><div className="quick-links"><ArrowLink href="/student-hub" label="Join Zoom"/><ArrowLink href="/schedule" label="Schedule"/><ArrowLink href="/resources" label="Practice"/><ArrowLink href="/payment" label="Pay"/></div></div><div className="path path-new"><p className="eyebrow">Not sure where to begin?</p><h2>New students</h2><div className="quick-links dark-links"><ArrowLink href="/services" label="Services"/><ArrowLink href="/locations" label="Locations"/><ArrowLink href="/preassessment" label="Preassessment"/></div></div></section>
    <section className="home-intro section-wrap"><div><p className="eyebrow">The right kind of help</p><h2>Support that starts with the learner—not a worksheet.</h2></div><div><p>I identify what a learner can do independently, where guidance is needed, and where frustration begins. Then we build forward with clear teaching, guided practice, and steady movement toward independence.</p><Link className="text-link" href="/approach">See how tutoring works →</Link></div></section>
    <section className="rate-band"><div><p className="eyebrow light">One clear rate</p><h2>$40 <small>/ hour</small></h2></div><p>Pay weekly, biweekly, or monthly.<br/><strong>Payment is due 24 hours before each session.</strong></p><Link className="button cream" href="/pricing">See pricing & policies →</Link></section>
    <section className="loop-band"><div><p className="eyebrow">Stay in the loop</p><h2>Openings, updates & learning tips.</h2></div><form className="email-form"><label className="sr-only" htmlFor="home-email">Email address</label><input id="home-email" type="email" placeholder="Your email address" required/><