import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {CTA,ExternalButton,Icon,links,PageHero,SitePage} from "../site-components";

const pageSlugs=["services","approach","locations","pricing","about","faq","preassessment","student-hub","schedule","resources","payment","contact"] as const;
const meta:Record<string,[string,string]>={services:["Tutoring Services","Reading, math, GED, adult learning, homework, and homeschool tutoring services."],approach:["How Tutoring Works","Learn how Miss Arnold identifies needs, teaches clearly, guides practice, and builds independence."],locations:["Tutoring Locations","Zoom, Lexington County Main Library, and approved in-home tutoring options."],pricing:["Tutoring Pricing & Policies","Clear $40 hourly tutoring rates, payment options, travel fees, and policies."],about:["About Miss Arnold","Meet Claire Arnold, a certified South Carolina educator and reading interventionist."],faq:["Frequently Asked Questions","Answers for parents and adult learners about tutoring, pricing, scheduling, and getting started."],preassessment:["Book a Pre-Assessment","Begin tutoring with an in-person or Zoom pre-assessment."],"student-hub":["Current Student Hub","Zoom, scheduling, practice, payment, and contact links for current students."],schedule:["Book or Reschedule","View available tutoring appointments through Google Calendar."],resources:["Student Resources","Information about assigned practice sheets and Blooket reviews."],payment:["Make a Payment","Pay for tutoring securely through Square."],contact:["Contact Miss Arnold","Get started or ask a question about tutoring support."]};
export function generateStaticParams(){return pageSlugs.map(slug=>({slug}))}
export const dynamicParams=false;
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const item=meta[slug];return item?{title:`${item[0]} | Miss Arnold’s Tutoring Table`,description:item[1]}:{}}

const serviceCards=[
  ["book","Reading Support","Phonics, decoding, fluency, comprehension, vocabulary, writing, and confidence-building for developing readers."],
  ["math","Math Support","Foundational skills through pre-algebra, including operations, fractions, decimals, measurement, and problem solving."],
  ["cap","GED & Adult Learning","Foundational math, GED preparation, ASVAB preparation, and patient support for adults returning to learning."],
  ["check","Homework & Study Skills","Help understanding directions, organizing thinking, learning the skill, and completing work more independently."],
  ["home","Homeschool Support","Targeted instruction, skill checks, practice, and support based on the learner’s current needs."],
  ["heart","IEP, 504 & Dyslexia-Aware Support","Instruction that considers accommodations, learning needs, evaluations, and family concerns."],
] as const;

const faqs=[
  ["Who do you tutor?","Miss Arnold’s Tutoring Table primarily serves students in Grades 2–7 and adult learners. Learners outside these levels may be considered individually based on subject and need."],
  ["What subjects do you teach?","Reading, math, writing, foundational academic skills, homework and study skills, GED preparation, and ASVAB preparation."],
  ["What happens during the pre-assessment?","The pre-assessment is our first session together. Miss Arnold meets the learner, discusses concerns and goals, observes current skills, and identifies an appropriate starting point. It can take place in person or through Zoom."],
  ["How much does tutoring cost?","Tutoring is $40 per hour. A 30-minute session is $20. Families may arrange weekly, biweekly, or monthly payments."],
  ["When is payment due?","Payment must be received at least 24 hours before the scheduled tutoring session."],
  ["Where are sessions held?","Sessions are available online through Zoom, at Lexington County Main Library, or in approved homes within Lexington and West Columbia."],
  ["Is there a travel fee?","Yes. A flat $10 travel fee is added to each in-home visit in Lexington or West Columbia."],
  ["Do you work with IEPs, 504 Plans, or dyslexia?","Yes. Families may share relevant documents and accommodations so instruction can better support the learner’s needs."],
  ["Will you complete homework for my child?","No. Homework support helps learners understand directions, practice the needed skill, and complete work more independently."],
  ["How do schedule changes work?","Use the booking calendar to request an available time. An existing appointment remains scheduled until the replacement is booked or Miss Arnold confirms the change."],
  ["What is the refund policy?","Payments are generally nonrefundable. When possible, Miss Arnold works with families to reschedule an eligible missed session instead of issuing a refund. Rescheduling depends on notice and availability."],
  ["How does Zoom entry work?","Participants enter the Zoom waiting room and must be admitted by Miss Arnold. Opening the meeting link does not provide automatic entry."],
];

function Services(){return <SitePage><PageHero kicker="Personalized support" title="Services built around the learner." intro="Focused one-on-one tutoring for Grades 2–7 and adults—without a one-size-fits-all program."/><section className="card-grid section-wrap">{serviceCards.map(([icon,title,text])=><article key={title}><Icon name={icon}/><h2>{title}</h2><p>{text}</p><Link className="text-link" href="/preassessment">Request support →</Link></article>)}</section><CTA/></SitePage>}

function Approach(){const steps=[["calendar","Book a Pre-Assessment","Choose in-person or Zoom and complete the intake information before the first session."],["check","Understand the Learner","We identify strengths, skill gaps, confidence, goals, and the point where frustration begins."],["book","Teach and Practice","Skills are explained clearly, practiced together, and supported with visuals or hands-on tools when useful."],["person","Build Independence","Support is gradually reduced so the learner can apply skills, explain thinking, and recognize progress."]] as const;return <SitePage><PageHero kicker="What families can expect" title="A clear process from the first session forward." intro="Parents and adult learners always know what we are working on, why it matters, and what comes next." tone="green"/><section className="steps section-wrap">{steps.map(([icon,title,text],i)=><article key={title}><b>{i+1}</b><Icon name={icon}/><div><h2>{title}</h2><p>{text}</p></div></article>)}</section><section className="quote-band"><blockquote>Struggling academically does not mean a learner is incapable. Sometimes the information simply needs to be presented differently.</blockquote><Link className="button cream-button" href="/about">Meet Miss Arnold →</Link></section><CTA/></SitePage>}

function Locations(){return <SitePage><PageHero kicker="Flexible ways to learn" title="Choose the setting that works for you." intro="Tutoring is available online and in person around Lexington, South Carolina."/><section className="location-grid section-wrap"><article><Icon name="laptop"/><h2>Online through Zoom</h2><p>Interactive one-on-one sessions from home using shared learning materials and digital tools.</p><ul><li>Available beyond Lexington</li><li>Waiting-room admission required</li><li>Miss Arnold must admit each participant</li></ul><div className="stack-buttons"><ExternalButton href={links.zoom} className="green-button">Join Zoom Session →</ExternalButton></div></article><article><Icon name="pin"/><h2>Lexington County Main Library</h2><p>5440 Augusta Road<br/>Lexington, SC</p><ul><li>Comfortable public learning space</li><li>Location confirmed before the session</li></ul><div className="stack-buttons"><ExternalButton href={links.googleMaps} className="green-button">Google Maps Directions</ExternalButton><ExternalButton href={links.appleMaps}>Apple Maps Directions</ExternalButton></div></article><article><Icon name="home"/><h2>In-Home Tutoring</h2><p>Approved in-home sessions are available in Lexington and West Columbia.</p><ul><li>$10 travel fee per visit</li><li>Availability depends on location and schedule</li><li>Address confirmed privately</li></ul></article></section><CTA/></SitePage>}

function Pricing(){return <SitePage><PageHero kicker="Straightforward pricing" title="Clear rates. No confusing packages." intro="All tutoring is billed at the same $40 hourly rate, whether support is for a child or an adult learner." tone="coral"/><section className="pricing-layout section-wrap"><article className="main-price"><p>One-on-one tutoring</p><strong>$40</strong><span>per hour</span><ul><li><span>30 minutes</span><b>$20</b></li><li><span>1 hour</span><b>$40</b></li><li><span>2 hours</span><b>$80</b></li><li><span>3 hours</span><b>$120</b></li></ul></article><div className="policy-grid"><article><h2>Flexible Payment Schedule</h2><p>Pay weekly, biweekly, or monthly based on the confirmed tutoring schedule.</p></article><article><h2>Payment Deadline</h2><p>Payment must be received at least <strong>24 hours before</strong> the scheduled session.</p></article><article><h2>In-Home Travel Fee</h2><p>Add $10 for every in-home visit in Lexington or West Columbia.</p></article><article><h2>Rescheduling & Refunds</h2><p>Payments are generally nonrefundable. When eligible and space is available, sessions are normally rescheduled instead.</p></article><article className="payment-card"><h2>Pay Securely Online</h2><p>Square accepts major debit and credit cards. Apple Pay may be available on eligible devices. Cash App and Chime are available by request.</p><ExternalButton href={links.square} className="primary">Pay with Square →</ExternalButton></article></div></section><CTA/></SitePage>}

function About(){return <SitePage><PageHero kicker="Meet Miss Arnold" title="An educator who understands that learning can click differently." intro="Certified educator, former reading interventionist, tutor, and owner of Miss Arnold’s Tutoring Table."/><section className="about-layout section-wrap"><div className="about-photo" role="img" aria-label="Portrait area for Miss Arnold"><span>Miss Arnold</span></div><div><h2>Professional experience. Patient, individualized teaching.</h2><p>I’m Claire Arnold, a certified South Carolina educator, former K–8 reading interventionist, and the owner of Miss Arnold’s Tutoring Table. Before becoming a full-time tutor, I spent three years in public education—two years teaching middle school social studies and one year serving as a K–8 reading interventionist.</p><p>As both an educator and a person with dyslexia, I understand that struggling academically does not mean a learner is incapable. Sometimes information needs to be presented more clearly, broken into manageable steps, or connected to the way the learner thinks best.</p><p>I created Miss Arnold’s Tutoring Table to provide the individualized support that can be difficult to receive in a busy classroom. Lessons are structured, patient, purposeful, and tailored to each learner’s goals, confidence, interests, and needs.</p><aside><strong>The goal is bigger than finishing one assignment.</strong><br/>Learners should understand what they are doing, recognize their progress, and feel more prepared to attempt difficult things.</aside></div></section><CTA/></SitePage>}

function FAQ(){return <SitePage><PageHero kicker="Good questions are welcome" title="Answers for parents and adult learners." intro="Review the most common questions about tutoring, payments, locations, scheduling, and getting started."/><section className="faq-list section-wrap">{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section><CTA/></SitePage>}

function Preassessment(){return <SitePage><PageHero kicker="Your first session" title="Begin with an in-person or Zoom pre-assessment." intro="This first meeting helps Miss Arnold understand the learner, discuss goals, observe current skills, and select the right place to begin." tone="green"/><section className="getting-started section-wrap"><div><p className="eyebrow">Before you book</p><h2>Four simple steps</h2><ol><li><b>1</b><span><strong>Complete the intake form.</strong> Share the learner’s needs, goals, accommodations, and availability.</span></li><li><b>2</b><span><strong>Review the service agreement.</strong> Read the scheduling, payment, and tutoring expectations.</span></li><li><b>3</b><span><strong>Choose an available time.</strong> Select an in-person or Zoom appointment through Google Calendar.</span></li><li><b>4</b><span><strong>Wait for confirmation.</strong> The appointment is confirmed after Miss Arnold reviews the information.</span></li></ol></div><aside><h2>Start here</h2><p>These links open secure Google forms and the booking calendar in a new tab.</p><ExternalButton href={links.intake} className="primary">1. Complete Intake Form</ExternalButton><ExternalButton href={links.agreement} className="green-button">2. Review Service Agreement</ExternalButton><ExternalButton href={links.calendar}>3. View Available Times</ExternalButton><small>Submitting a form or choosing a time does not confirm an appointment until Miss Arnold responds.</small></aside></section><CTA/></SitePage>}

function StudentHub(){return <SitePage><PageHero kicker="Current students" title="Everything you need, right at the table." intro="Access your session, booking calendar, payments, and assigned-resource information in one phone-friendly place." tone="green"/><section className="hub-grid section-wrap"><a href={links.zoom} target="_blank" rel="noopener noreferrer"><Icon name="laptop"/><h2>Join Zoom</h2><p>Open the tutoring room. You will enter the waiting room until Miss Arnold admits you.</p><b>Open Zoom →</b></a><a href={links.calendar} target="_blank" rel="noopener noreferrer"><Icon name="calendar"/><h2>Book or Reschedule</h2><p>View available appointments. Changes are not final until confirmed.</p><b>View Calendar →</b></a><Link href="/resources"><Icon name="book"/><h2>Practice Resources</h2><p>Review how assigned worksheets and Blooket activities are shared.</p><b>View Resources →</b></Link><a href={links.square} target="_blank" rel="noopener noreferrer"><Icon name="check"/><h2>Make a Payment</h2><p>Pay securely through Square at least 24 hours before the session.</p><b>Pay with Square →</b></a></section><section className="notice-band"><strong>Zoom waiting-room policy</strong><p>Every participant must be admitted by Miss Arnold. Opening the Zoom link does not provide immediate or automatic entry.</p></section></SitePage>}

function Schedule(){return <SitePage><PageHero kicker="Current students" title="Book or change a tutoring session." intro="Use Google Calendar to view current availability. Existing appointments remain scheduled until a replacement is booked or Miss Arnold confirms the change."/><section className="single-action section-wrap"><Icon name="calendar"/><h2>View Available Appointments</h2><p>Choose the appointment that works best. For an ongoing schedule change or a question about an existing appointment, contact Miss Arnold before assuming the change is final.</p><ExternalButton href={links.calendar} className="primary">Open Booking Calendar →</ExternalButton><div className="notice"><strong>Important:</strong> Booking availability can change. A requested time is not guaranteed until confirmed.</div></section></SitePage>}

function Resources(){return <SitePage><PageHero kicker="Current student resources" title="Practice with a purpose." intro="Worksheets, Blooket reviews, and other activities are assigned according to each learner’s tutoring plan." tone="green"/><section className="resource-info section-wrap"><article><Icon name="book"/><h2>Assigned Practice</h2><p>Miss Arnold shares the specific worksheet or practice link selected for the learner. This prevents students from working on material that does not match the current lesson.</p></article><article><Icon name="laptop"/><h2>Blooket Reviews</h2><p>Assigned Blooket links are shared directly with current students when a review game supports the skill being practiced.</p></article><article><Icon name="check"/><h2>Need Your Link?</h2><p>If an assigned resource is missing or will not open, contact Miss Arnold for the correct link. No inactive resource buttons are displayed here.</p><Link className="text-link" href="/contact">Contact Miss Arnold →</Link></article></section></SitePage>}

function Payment(){return <SitePage><PageHero kicker="Current families" title="Make a tutoring payment." intro="Pay securely through Square at least 24 hours before the scheduled tutoring session."/><section className="payment-layout section-wrap"><article><p>Standard tutoring rate</p><strong>$40</strong><span>per hour</span><hr/><p><b>In-home visits:</b> Add the $10 travel fee for each Lexington or West Columbia visit.</p></article><div><h2>Secure Online Payment</h2><p>Square accepts major credit and debit cards. Apple Pay may also appear at checkout on eligible devices.</p><ExternalButton href={links.square} className="primary">Pay Securely with Square →</ExternalButton><small>You will be taken to Square’s secure checkout.</small><hr/><h3>Other payment methods</h3><p>Cash App and Chime are available by request. Contact Miss Arnold for the correct information before sending funds.</p></div></section></SitePage>}

function Contact(){return <SitePage><PageHero kicker="Let’s connect" title="Questions before you begin?" intro="Choose the option that best matches what you need."/><section className="contact-grid section-wrap"><article><Icon name="person"/><h2>New Families & Learners</h2><p>Complete the intake information and review the service agreement before requesting your first session.</p><Link className="button primary" href="/preassessment">Start Here</Link></article><article><Icon name="calendar"/><h2>Current Students</h2><p>Use the Student Hub for Zoom, scheduling, payments, and resource information.</p><Link className="button green-button" href="/student-hub">Open Student Hub</Link></article><article><Icon name="heart"/><h2>Still Have Questions?</h2><p>The FAQ explains grade levels, pricing, locations, Zoom entry, scheduling, rescheduling, and refunds.</p><Link className="button secondary" href="/faq">Read the FAQ</Link></article></section></SitePage>}

export default async function SlugPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const pages:Record<string,React.ReactNode>={services:<Services/>,approach:<Approach/>,locations:<Locations/>,pricing:<Pricing/>,about:<About/>,faq:<FAQ/>,preassessment:<Preassessment/>,"student-hub":<StudentHub/>,schedule:<Schedule/>,resources:<Resources/>,payment:<Payment/>,contact:<Contact/>};return pages[slug]??notFound()}
