import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHero, SitePage } from "../site-components";

const serviceCards=[
  ["Reading support","Phonics, decoding, fluency, comprehension, vocabulary, and confidence-building for developing readers."],
  ["Math support","Foundational skills through pre-algebra, including place value, operations, fractions, decimals, and problem solving."],
  ["Adult learning","Foundational math, GED preparation, ASVAB preparation, and patient support for adults returning to learning."],
  ["Homework & study skills","Help understanding directions, organizing thinking, learning the skill, and completing work more independently."],
  ["Homeschool support","Targeted instruction, skill checks, practice, and support aligned to your learner’s current needs."],
  ["IEP & 504 support","Instruction that considers accommodations, learning needs, school evaluations, and family concerns."],
];
const faqs=[
  ["What ages and grade levels do you tutor?","Miss Arnold’s Tutoring Table primarily serves students in Grades 2–7 and adult learners. Students outside these levels may be considered individually based on their needs and subject."],
  ["What subjects do you teach?","Reading, math, writing, foundational academic skills, homework support, study skills, GED preparation, and ASVAB preparation."],
  ["How much does tutoring cost?","All tutoring is $40 per hour. A 30-minute session is $20. Families may arrange weekly, biweekly, or monthly payments."],
  ["When is payment due?","Payment must be received at least 24 hours before the scheduled tutoring session."],
  ["Where are sessions held?","Online through Zoom, at the Lexington Main Library, or in approved homes within Lexington and West Columbia."],
  ["Is there a travel fee?","Yes. In-home tutoring in Lexington or West Columbia includes a $10 travel fee for each visit."],
  ["Do you work with IEPs, 504 Plans, or dyslexia?","Yes. Relevant documents and accommodations can help Miss Arnold better understand and support the learner’s needs."],
  ["Do you complete homework for students?","No. Homework support teaches students how to understand directions, use the needed skill, and work more independently."],
  ["Can I change a scheduled session?","Current families can request a change through the Student Hub. The change is not confirmed until Miss Arnold approves it."],
  ["What is a preassessment?","The preassessment is the learner’s first session with Miss Arnold. It takes place in person or through Zoom and gives Miss Arnold time to meet the learner, discuss goals, observe current skills, and determine the best starting point for tutoring."],
  ["How do new students begin?","Submit a request with the learner’s needs, goals, preferred preassessment location, and availability. Miss Arnold will contact you to schedule the first session."],
];

function Services(){return <SitePage><PageHero kicker="Personalized support" title="Services built around the learner." intro="Focused one-on-one tutoring for Grades 2–7 and adults—without a one-size-fits-all program."/><section className="card-grid section-wrap">{serviceCards.map(([t,d],i)=><article className="service-card" key={t}><span>0{i+1}</span><h2>{t}</h2><p>{d}</p><Link href="/preassessment">Request support →</Link></article>)}</section><CTA/></SitePage>}
function Approach(){return <SitePage><PageHero kicker="The Miss Arnold method" title="Clear teaching. Guided practice. Real independence." intro="Tutoring begins with what the learner understands today and builds toward what they need next." accent="green-hero"/><section className="steps section-wrap"><Step n="01" title="Understand the learner" text="We identify strengths, skill gaps, goals, confidence, and the point where frustration begins."/><Step n="02" title="Teach it clearly" text="New skills are broken into manageable steps using explicit instruction, visuals, examples, and hands-on support."/><Step n="03" title="Practice together" text="Guided practice gives the learner enough support to think through the process without being given the answer."/><Step n="04" title="Build independence" text="Support is gradually removed so the learner can apply the skill, explain their thinking, and recognize their progress."/></section><section className="quote-band"><blockquote>“Struggling academically does not mean a learner is incapable. Sometimes the information simply needs to be presented differently.”</blockquote><Link className="button cream" href="/about">Meet Miss Arnold →</Link></section></SitePage>}
function Locations(){return <SitePage><PageHero kicker="Flexible ways to learn" title="Choose the setting that fits." intro="Tutoring is available online and in person around Lexington, South Carolina."/><section className="location-grid section-wrap"><InfoCard icon="⌁" title="Online through Zoom" text="Interactive one-on-one tutoring with digital whiteboard tools and shared learning materials." points={["Secure link inside Student Hub","Available beyond Lexington","Works well for consistent scheduling"]}/><InfoCard icon="⌖" title="Lexington County Main Library" text="A comfortable, public learning space at 5440 Augusta Road, Lexington, SC." points={["Quiet one-on-one instruction","Location confirmed before session"]} maps/><InfoCard icon="⌂" title="In-home tutoring" text="Approved in-home sessions are available within Lexington and West Columbia." points={["$10 travel fee per visit","Available in Lexington and West Columbia","Availability depends on schedule"]}/></section><CTA/></SitePage>}
function Pricing(){return <SitePage><PageHero kicker="Straightforward pricing" title="Clear rates. Personalized support." intro="Tutoring is $40 per hour, with session lengths selected to match the learner’s goals and attention needs." accent="terracotta-hero"/><section className="pricing-wrap section-wrap"><div className="price-card"><p className="rate-label">One-on-one tutoring</p><div className="price-display"><strong>$40</strong><span>per hour</span></div><p className="rate-note">Focused instruction designed around one learner—not a group or a standard program.</p><ul><li><span>30 minutes</span><b>$20</b></li><li><span>1 hour</span><b>$40</b></li><li><span>2 hours</span><b>$80</b></li><li><span>3 hours</span><b>$120</b></li></ul></div><div className="policy-stack"><article><span className="policy-label">Payment schedule</span><h2>Choose your rhythm</h2><p>Families may pay weekly, biweekly, or monthly based on their confirmed tutoring schedule.</p></article><article><span className="policy-label">Before your session</span><h2>Payment deadline</h2><p>Payment must be received at least <strong>24 hours before</strong> the scheduled tutoring session.</p></article><article><span className="policy-label">Convenient options</span><h2>Ways to pay</h2><p>Square, Cash App, Chime, Apple Pay, and PayPal are accepted. Instructions are provided after scheduling.</p></article><article className="travel-policy"><span className="policy-label">In-home tutoring</span><h2>$10 travel fee</h2><p>A flat $10 travel fee is added to each in-home visit in Lexington or West Columbia.</p></article></div></section><CTA/></SitePage>}
function About(){return <SitePage><PageHero kicker="Meet Miss Arnold" title="An educator who knows that learning can click differently." intro="Certified educator, reading interventionist, tutor, and owner of Miss Arnold’s Tutoring Table."/><section className="about-layout section-wrap"><div className="portrait-card"><div className="portrait-shape"><span>CA</span></div><p>Claire Arnold<br/><small>Certified South Carolina Educator</small></p></div><div className="long-copy"><p>I’m Claire Arnold, a certified South Carolina educator, reading interventionist, and the owner of Miss Arnold’s Tutoring Table. Before becoming a full-time tutor, I spent three years in public education—two years teaching middle school social studies and one year serving as a K–8 reading interventionist. I also bring more than five years of tutoring experience with elementary, middle school, and adult learners.</p><p>As both an educator and a person with dyslexia, I understand that struggling academically does not mean a student is incapable. Sometimes a learner needs information presented more clearly, broken into manageable steps, or connected to the way their mind works best. That perspective shapes everything I do.</p><p>I created Miss Arnold’s Tutoring Table to provide the individualized support that can be difficult to receive in a busy classroom. My approach is structured, patient, and purposeful. Lessons are tailored to the learner’s goals, interests, confidence level, and learning style—not pulled from a one-size-fits-all program.</p><p>The goal is bigger than completing one assignment or earning one good grade. I want learners to understand what they are doing, recognize their progress, and develop the confidence to attempt difficult things without immediately believing they cannot succeed.</p><aside><strong>Learning does not have to look the same for everyone.</strong><br/>It simply needs to click—and the right support can help make that happen.</aside></div></section><CTA/></SitePage>}
function FAQ(){return <SitePage><PageHero kicker="Good questions are welcome" title="Frequently asked questions." intro="Clear answers about tutoring, payment, locations, learning support, and getting started."/><section className="faq-list section-wrap">{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section><CTA/></SitePage>}
function Preassessment(){return <SitePage><PageHero kicker="Your first tutoring session" title="Start with an in-person or Zoom preassessment." intro="The preassessment is our first session together. It gives me time to meet the learner, understand the concern, observe current skills, and choose the right place to begin." accent="green-hero"/><section className="form-layout section-wrap"><div className="form-side"><h2>How it works</h2><ol><li><span>1</span>Share the learner’s needs, goals, and availability.</li><li><span>2</span>Choose an in-person or Zoom preassessment.</li><li><span>3</span>Miss Arnold contacts you to schedule the first session.</li><li><span>4</span>During the session, we identify strengths, skill gaps, and the best starting point.</li></ol></div><form className="intake-form" action="/preassessment"><Field label="Your name"/><Field label="Email address" type="email"/><Field label="Phone number" type="tel"/><Field label="Learner’s name"/><label>Who needs support?<select><option>Student in Grades 2–7</option><option>Adult learner</option><option>Homeschool learner</option><option>ASVAB learner</option><option>Outside the primary age range</option></select></label><label>Area of support<select><option>Reading</option><option>Math</option><option>Writing</option><option>GED preparation</option><option>ASVAB preparation</option><option>Homework / study skills</option><option>Not sure yet</option></select></label><label>Preferred preassessment location<select><option>Zoom</option><option>Lexington County Main Library</option><option>In-home: Lexington</option><option>In-home: West Columbia</option></select></label><label>What would you like Miss Arnold to know before the first session?<textarea rows={5} placeholder="Tell me about current concerns, goals, accommodations, and availability."/></label><button className="button primary" type="submit">Request my first session →</button><p className="form-note">Submitting this form requests an in-person or Zoom preassessment. Your first session is not confirmed until Miss Arnold contacts you.</p></form></section></SitePage>}
function StudentHub(){return <SitePage><section className="hub-hero"><div><p className="eyebrow light">Current students</p><h1>Everything you need, right at the table.</h1><p>Session access, schedule requests, practice, payments, and announcements in one phone-friendly place.</p></div><div className="hub-lock"><span>◉</span><h2>Student Hub sign in</h2><p>Enter the family access password provided by Miss Arnold.</p><label className="sr-only" htmlFor="hub-password">Family access password</label><input id="hub-password" type="password" placeholder="Access password"/><button className="button primary">Open my hub →</button><small>Need help? Contact Miss Arnold.</small></div></section><section className="hub-preview section-wrap"><p className="eyebrow">Inside your hub</p><div className="hub-grid"><HubCard icon="◉" title="Join Zoom" text="Contact Miss Arnold for secure tutoring-room access." href="/miss-arnold-s-tutoring-table/contact/" action="Request Zoom access"/><HubCard icon="↻" title="Book a time" text="View Miss Arnold’s current Google Calendar availability." href="https://calendar.app.google/7REHjA7DQgKz125U7" action="View available times"/><HubCard icon="✎" title="Practice" text="Find assigned sheets and Blooket reviews."/><HubCard icon="$" title="Make a payment" text="Pay securely by card or Apple Pay through Square." href="https://square.link/u/K6jriBfx" action="Pay with Square"/><HubCard icon="!" title="Announcements" text="See closures, reminders, and new resources."/><HubCard icon="→" title="Contact Miss Arnold" text="Get help with access or your tutoring plan."/></div><div className="zoom-notice"><strong>Zoom waiting-room policy</strong><p>All participants enter a waiting room and must be admitted by Miss Arnold. Opening the meeting link does not provide immediate or automatic entry to the tutoring session.</p></div></section></SitePage>}
function Schedule(){return <SitePage><PageHero kicker="Current students" title="Book or change a tutoring session." intro="View available appointments through Google Calendar. Existing sessions remain in place until a replacement time is booked or Miss Arnold confirms a requested change."/><section className="form-layout section-wrap"><div className="form-side"><h2>Choose an available time</h2><p>Use the booking calendar to view Miss Arnold’s current availability and select the appointment that works best.</p><a className="button primary calendar-button" href="https://calendar.app.google/7REHjA7DQgKz125U7" target="_blank" rel="noopener noreferrer">Open booking calendar →</a><div className="notice"><strong>Changing an existing session?</strong><p>Your current appointment stays scheduled until the new time is booked or the change is confirmed by Miss Arnold.</p></div></div><form className="intake-form"><Field label="Student name"/><label>Type of change<select><option>One session only</option><option>Ongoing schedule change</option></select></label><Field label="Current session date" type="date"/><Field label="First-choice replacement" type="datetime-local"/><Field label="Second-choice replacement" type="datetime-local"/><label>Anything else?<textarea rows={4}/></label><button className="button primary">Send schedule request →</button></form></section></SitePage>}
function Resources(){return <SitePage><PageHero kicker="Current-student resources" title="Practice with a purpose." intro="Assigned sheets, review games, and helpful tools organized by learning area." accent="green-hero"/><section className="resource-tabs section-wrap"><div className="filter-row"><button>All</button><button>Reading</button><button>Math</button><button>Adult / GED</button><button>ASVAB</button><button>Study skills</button></div><div className="resource-grid"><Resource type="Math" title="Fraction & decimal word problems" format="Practice sheet"/><Resource type="Reading" title="Fluency and comprehension review" format="Practice sheet"/><Resource type="Math" title="Multiplication facts review" format="Blooket"/><Resource type="Adult / GED" title="Foundational math practice" format="Practice set"/><Resource type="Study skills" title="Breaking down directions" format="Quick guide"/><Resource type="Reading" title="Phonics pattern review" format="Blooket"/></div><p className="form-note">Students will see materials assigned to their tutoring plan after signing in.</p></section></SitePage>}
function Payment(){return <SitePage><PageHero kicker="Current families" title="Make a tutoring payment." intro="Pay securely through Square at least 24 hours before your scheduled session."/><section className="payment-layout section-wrap"><div className="payment-reminder"><p>Standard rate</p><strong>$40/hour</strong><span>Weekly, biweekly, or monthly</span><hr/><p><b>Due:</b> At least 24 hours before the scheduled tutoring session.</p><p><b>In-home visits:</b> Add the $10 travel fee for each Lexington or West Columbia visit.</p></div><div className="pay-options"><h2>Secure online payment</h2><p>Square accepts major credit and debit cards. Apple Pay may also appear at checkout on eligible devices.</p><a className="square-pay-button" href="https://square.link/u/K6jriBfx" target="_blank" rel="noreferrer">Pay securely with Square <span>→</span></a><small>You will be taken to Square’s secure checkout to complete your payment.</small><hr/><h3>Other payment methods</h3><p>Cash App and Chime are available by request. Contact Miss Arnold for the correct payment details before sending funds.</p></div></section></SitePage>}
function Contact(){return <SitePage><PageHero kicker="Let’s connect" title="Questions before you begin?" intro="Send a message or request a preassessment when you are ready to discuss tutoring support."/><section className="form-layout section-wrap"><div className="form-side"><h2>Miss Arnold’s Tutoring Table</h2><p>Serving Grades 2–7 and adult learners in Lexington, West Columbia, and online.</p><p><strong>New families:</strong><br/>The preassessment form is the best place to begin.</p><Link className="button secondary" href="/preassessment">Request a preassessment →</Link></div><form className="intake-form"><Field label="Name"/><Field label="Email" type="email"/><Field label="Phone" type="tel"/><label>How can I help?<textarea rows={6}/></label><button className="button primary">Send message →</button></form></section></SitePage>}

function Step({n,title,text}:{n:string,title:string,text:string}){return <article><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></article>}
function InfoCard({icon,title,text,points,maps=false}:{icon:string,title:string,text:string,points:string[],maps?:boolean}){return <article className="info-card"><span>{icon}</span><h2>{title}</h2><p>{text}</p><ul>{points.map(p=><li key={p}>{p}</li>)}</ul>{maps&&<div className="map-buttons"><a href="https://www.google.com/maps/dir/?api=1&destination=5440+Augusta+Road%2C+Lexington%2C+SC" target="_blank" rel="noopener noreferrer">Google Maps directions ↗</a><a href="https://maps.apple.com/?daddr=5440+Augusta+Road%2C+Lexington%2C+SC" target="_blank" rel="noopener noreferrer">Apple Maps directions ↗</a></div>}</article>}
function Field({label,type="text"}:{label:string,type?:string}){return <label>{label}<input type={type} required/></label>}
function CTA(){return <section className="cta-band"><div><p className="eyebrow light">Ready to begin?</p><h2>Let’s find the right starting point.</h2></div><Link className="button cream" href="/preassessment">Request a preassessment →</Link></section>}
function HubCard({icon,title,text,href,action}:{icon:string,title:string,text:string,href?:string,action?:string}){const content=<><span>{icon}</span><h2>{title}</h2><p>{text}</p>{href&&<b>{action??"Open"} →</b>}</>;return href?<a className="hub-card" href={href} target="_blank" rel="noreferrer">{content}</a>:<article>{content}</article>}
function Resource({type,title,format}:{type:string,title:string,format:string}){return <article><p>{type}</p><h2>{title}</h2><span>{format}</span><button>Open resource →</button></article>}
const pageSlugs=["services","approach","locations","pricing","about","faq","preassessment","student-hub","schedule","resources","payment","contact"];
export function generateStaticParams(){return pageSlugs.map(slug=>({slug}))}
export const dynamicParams=false;
export default async function SlugPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const pages:Record<string,React.ReactNode>={services:<Services/>,approach:<Approach/>,locations:<Locations/>,pricing:<Pricing/>,about:<About/>,faq:<FAQ/>,preassessment:<Preassessment/>,"student-hub":<StudentHub/>,schedule:<Schedule/>,resources:<Resources/>,payment:<Payment/>,contact:<Contact/>};return pages[slug]??notFound()}
