import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHero, SitePage } from "../site-components";

const serviceCards=[
  ["Reading support","Phonics, decoding, fluency, comprehension, vocabulary, and confidence-building for developing readers."],
  ["Math support","Foundational skills through pre-algebra, including place value, operations, fractions, decimals, and problem solving."],
  ["Adult learning","Foundational math, GED preparation, ASVAB preparation, and patient support for adults returning to learning."],
  ["Homework & study skills","Help understanding directions, organizing thinking, learning the skill, and completing work more independently."],
  ["Homeschool support","Targeted instruction, skill checks, practice, and support aligned to your learner’s current needs."],
  ["IEP & 504 support","Instruction that considers accommodations, learning needs, school evaluations, and family concerns."],
];
const faqs=[
  ["What ages and grade levels do you tutor?","Miss Arnold’s Tutoring Table primarily serves students in Grades 2–7 and adult learners. Students outside these levels may be considered individually based on their needs and subject."],
  ["What subjects do you teach?","Reading, math, writing, foundational academic skills, homework support, study skills, GED preparation, and ASVAB preparation."],
  ["How much does tutoring cost?","All tutoring is $40 per hour. A 30-minute session is $20. Families may arrange weekly, biweekly, or monthly payments."],
  ["When is payment due?","Payment must be received at least 24 hours before the scheduled tutoring session."],
  ["Where are sessions held?","Online through Zoom, at the Lexington Main Library, or in approved homes within Lexington and West Columbia."],
  ["Is there a travel fee?","Yes. In-home tutoring in Lexington or West Columbia includes a $10 travel fee for each visit."],
  ["Do you work with IEPs, 504 Plans, or dyslexia?","Yes. Relevant documents and accommodations can help Miss Arnold better understand and support the learner’s needs."],
  ["Do you complete homework for students?","No. Homework support teaches students how to understand directions, use the needed skill, and work more independently."],
  ["Can I change a scheduled session?","Current families can request a change through the Student Hub. The change is not confirmed until Miss Arnold approves it."],
  ["What is a preassessment?","The preassessment is the learner’s first session with Miss Arnold. It takes place in person or through Zoom and gives Miss Arnold time to meet the learner, discuss goals, observe current skills, and determine the best starting point for tutoring."],
  ["How do new students begin?","Submit a request with the learner’s needs, goals, preferred preassessment location, and availability. Miss Arnold will contact you to schedule the first session."],
];

function Services(){return <SitePage><PageHero kicker="Personalized support" title="Services built around the learner." intro="Focused one-on-one tutoring for Grades 2–7 and adults—without a one-size-fits-all program."/><section className="card-grid section-wrap">{serviceCards.map(([t,d],i)=><article className="service-card" key={t}><span>0{i+1}</span><h2>{t}</h2><p>{d}</p><Link href="/preassessment">Request support →</Link></article>)}</section><CTA/></SitePage>}
function Approach(){return <SitePage><PageHero kicker="The Miss Arnold method" title="Clear teaching. Guided practice. Real independence." intro="Tutoring begins with what the learner understands today and builds toward what they need next." accent="green-hero"/><section className="steps section-wrap"><Step n="01" title="Understand the learner" text="We identify strengths, skill gaps, goals, confidence, and the point where frustration begins."/><Step n="02" title="Teach it clearly" text="New skills are broken into manageable steps using explicit instruction, visuals, examples, and hands-on support."/><Step n="03" title="Practice together" text="Guided practice gives the learner enough support to think through the process without being given the answer."/><Step n="04" title="Build independence" text="Support is gradually removed so the learner can apply the skill, explain their thinking, and recognize their progress."/></section><section className="quote-band"><blockquote>“Struggling academically does not mean a learner is incapable. Sometimes the information simply needs to be presented differently.”</blockquote><Link className="button cream" href="/about">Meet Miss Arnold →</Link></section></SitePage>}
function Locations(){return <SitePage><PageHero kicker="Flexible ways to learn" title="Choose the setting that fits." intro="Tutoring is available online and in person around Lexington, South Carolina."/><section className="location-grid section-wrap"><InfoCard icon="⌁" title="Online through Zoom" text="Interactive one-on-one tutoring with digital whiteboard tools and shared learning materials." points={["Secure link inside Student Hub","Available beyond Lexington","Works well for consistent scheduling"]}/><InfoCard icon="⌖" title="Lexington County Main Library" text="A comfortable, public learning space at 5440 Augusta Road, Lexington, SC." points={["Quiet one-on-one instruction","Location confirmed before session"]} maps/><InfoCard icon="⌂" title="In-home tutoring" text="Approved in-home sessions are available within Lexington and West Columbia." points={["$10 travel fee per visit","Available in Lexington and West Columbia","Availability depends on schedule"]}/></section><CTA/></SitePage>}
function Pricing(){return <SitePage><PageHero kicker="Straightforward pricing" title="Clear rates. Personalized support." intro="Tutoring is $40 per hour, with session lengths selected to match the learner’s goals and attention needs." accent="terracotta-hero"/><section className="pricing-wrap section-wrap"><div className="price-card"><p className="rate-label">One-on-one tutoring</p><div className="price-display"><strong>$40</strong><span>per hour</span></div><p className="rate-note">Focused instruction designed around one learner—not a group or a standard program.</p><ul><li><span>30 minutes</span><b>$20</b></li><li><span>1 hour</span><b>$40</b></li><li><span>2 hours</span><b>$80</b></li><li><span>3 hours</span><b>$120</b></li></ul></div><div className="policy-stack"><article><span className="policy-label">Payment schedule</span><h2>Choose your rhythm</h2><p>Families may pay weekly, biweekly, or monthly based on their confirmed tutoring schedule.</p></article><article><span className="policy-label">Before your session</span><h2>Payment deadline</h2><p>Payment must be received at least <strong>24 hours before</strong> the scheduled tutoring session.</p></article><article><span className="policy-label">Convenient options</span><h2>Ways to pay</h2><p>Square, Cash App, Chime, Apple Pay, and PayPal are accepted. Instructions are provided after scheduling.</p></article><article className="travel-policy"><span className="policy-label">In-home tutoring</span><h2>$10 travel fee</h2><p>A flat $10 travel fee is added to each in-home visit in Lexington or West Columbia.</p></article></div></section><CTA/></SitePage>}
function About(){return <SitePage><PageHero kicker="Meet Miss Arnold" title="An educator who knows that learning can click differently." intro="Certified educator, reading interventionist, tutor, and owner of Miss Arnold’s Tutoring Table."/><section className="about-layout section-wrap"><div className="portrait-card"><div className="portrait-shape"><span>CA</span></div><p>Claire Arnold<br/><small>Certified South Carolina Educator</small></p></div><div className="long-copy"><p>I’m Claire Arnold, a certified South Carolina educator, reading interventionist, and the owner of Miss Arnold’s Tutoring Table. Before becoming a full-time tutor, I spent three years in public education—two years teaching middle school social studies and one year serving as a K–8 reading interventionist. I also bring more than five years of tutoring experience with elementary, middle school, and adult learners.</p><p>As both an educator and 